language: rust
rust:
# Reenable once Rust edition is available in stable
#  - stable
#  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo test --verbose --no-run
matrix:
  allow_failures:
    - rust: nightly
