cargo-features = ["edition"]

[package]
name = "bme680"
version = "0.3.1"
authors = ["marcelbuesing <buesing.marcel@googlemail.com>"]
description = "A pure Rust implementation for the BME680 environmental sensor."
repository = "https://github.com/marcelbuesing/bme680-hal"
documentation = "https://docs.rs/bme680"
license = "MIT"
edition = "2018"

[dependencies]
bitflags = "1.0"
embedded-hal = "0.2"
log = "0.4"

[dev-dependencies]
env_logger = "0.5"
i2cdev = "0.3"
influent = "0.4"
linux-embedded-hal = "0.2"
